function [ ] = savesims_q300_B3state( sp_f, sp_q300_f, ra_f, savespecies, sp_q300 )
%UNTITLED16 Summary of this function goes here
%   Detailed explanation goes here
writetable(array2table(transpose(savespecies),'VariableNames',{'A1',...
    'Anonsense1',...
    'Aprime1',...
    'B1',...
    'Burst1_onorig_targ_allele1',...
    'Burst1_onpara_targ_allele1',...
    'Burst1_off_targ_allele1',...
    'Burst1_onorig_targ_allele2',...
    'Burst1_onpara_targ_allele2',...
    'Burst1_off_targ_allele2',...
    'Burst1_on_para_allele1',...
    'Burst1_on_para_allele2',...
    'Burst1_on_orig_allele1',...
    'Burst1_on_orig_allele2',...
    'Burst1_is_mutated_allele1',...
    'Burst1_is_mutated_allele2'}), sp_f, 'Delimiter', ',')
writetable(ra_1_s,ra_f,'Delimiter',',')

writetable(array2table(transpose(sp_q300),'VariableNames',{'A1',...
    'Anonsense1',...
    'Aprime1',...
    'B1',...
    'Burst1_onorig_targ_allele1',...
    'Burst1_onpara_targ_allele1',...
    'Burst1_off_targ_allele1',...
    'Burst1_onorig_targ_allele2',...
    'Burst1_onpara_targ_allele2',...
    'Burst1_off_targ_allele2',...
    'Burst1_on_para_allele1',...
    'Burst1_on_para_allele2',...
    'Burst1_on_orig_allele1',...
    'Burst1_on_orig_allele2',...
    'Burst1_is_mutated_allele1',...
    'Burst1_is_mutated_allele2',...
    'time'}), sp_q300_f, 'Delimiter', ',')

end

